package playcanvas;

@:jsRequire("playcanvas", "ImageElement") extern class ImageElement {
	function new(element:Dynamic);
	var _element : Dynamic;
	var _entity : Dynamic;
	var _system : Dynamic;
	var _textureAsset : Dynamic;
	var _texture : Dynamic;
	var _materialAsset : Dynamic;
	var _material : Dynamic;
	var _spriteAsset : Dynamic;
	var _sprite : Dynamic;
	var _spriteFrame : Float;
	var _pixelsPerUnit : Dynamic;
	var _targetAspectRatio : Float;
	var _rect : Vec4;
	var _mask : Bool;
	var _maskRef : Float;
	var _outerScale : Vec2;
	var _outerScaleUniform : js.lib.Float32Array;
	var _innerOffset : Vec4;
	var _innerOffsetUniform : js.lib.Float32Array;
	var _atlasRect : Vec4;
	var _atlasRectUniform : js.lib.Float32Array;
	var _defaultMesh : Mesh;
	var _renderable : ImageRenderable;
	var _color : Color;
	var _colorUniform : js.lib.Float32Array;
	var _updateAabbFunc : Dynamic;
	function destroy():Void;
	var textureAsset : Dynamic;
	var spriteAsset : Dynamic;
	var materialAsset : Dynamic;
	function _onResolutionChange(res:Dynamic):Void;
	function _onParentResizeOrPivotChange():Void;
	function _onScreenSpaceChange(value:Dynamic):Void;
	function _onScreenChange(screen:Dynamic, previous:Dynamic):Void;
	function _onDrawOrderChange(order:Dynamic):Void;
	function _hasUserMaterial():Bool;
	function _use9Slicing():Bool;
	function _updateMaterial(screenSpace:Dynamic):Void;
	function _createMesh():Mesh;
	function _updateMesh(mesh:Dynamic):Void;
	var _meshDirty : Bool;
	function _updateSprite():Void;
	var mesh : Dynamic;
	function refreshMesh():Void;
	function _updateAabb(aabb:Dynamic):Dynamic;
	function _toggleMask():Void;
	function _onMaterialLoad(asset:Dynamic):Void;
	var material : Dynamic;
	function _onMaterialAdded(asset:Dynamic):Void;
	function _bindMaterialAsset(asset:Dynamic):Void;
	function _unbindMaterialAsset(asset:Dynamic):Void;
	function _onMaterialChange():Void;
	function _onMaterialRemove():Void;
	function _onTextureAdded(asset:Dynamic):Void;
	function _bindTextureAsset(asset:Dynamic):Void;
	function _unbindTextureAsset(asset:Dynamic):Void;
	function _onTextureLoad(asset:Dynamic):Void;
	var texture : Dynamic;
	function _onTextureChange(asset:Dynamic):Void;
	function _onTextureRemove(asset:Dynamic):Void;
	function _onSpriteAssetAdded(asset:Dynamic):Void;
	function _bindSpriteAsset(asset:Dynamic):Void;
	function _unbindSpriteAsset(asset:Dynamic):Void;
	function _onSpriteAssetLoad(asset:Dynamic):Void;
	var sprite : Dynamic;
	function _onSpriteAssetChange(asset:Dynamic):Void;
	function _onSpriteAssetRemove(asset:Dynamic):Void;
	function _bindSprite(sprite:Dynamic):Void;
	function _unbindSprite(sprite:Dynamic):Void;
	function _onSpriteMeshesChange():Void;
	function _onSpritePpuChange():Void;
	function _onAtlasTextureChange():Void;
	function _onTextureAtlasLoad(atlasAsset:Dynamic):Void;
	function onEnable():Void;
	function onDisable():Void;
	function _setStencil(stencilParams:Dynamic):Void;
	var color : Color;
	var opacity : Float;
	var rect : Vec4;
	var spriteFrame : Float;
	var mask : Bool;
	var pixelsPerUnit : Dynamic;
	final aabb : Dynamic;
	static var prototype : ImageElement;
}