package global.pc;

@:native("pc.WorldClusters") extern class WorldClusters {
	function new(device:Dynamic);
	var clusterTexture : Texture;
	var device : Dynamic;
	var name : String;
	var reportCount : Float;
	var boundsMin : Vec3;
	var boundsMax : Vec3;
	var boundsDelta : Vec3;
	var _cells : Vec3;
	var _cellsLimit : Vec3;
	var cells : Vec3;
	var maxCellLightCount : Dynamic;
	var _maxAttenuation : Float;
	var _maxColorValue : Float;
	var _usedLights : Array<playcanvas.ClusterLight>;
	var lightsBuffer : playcanvas.LightsBuffer;
	var _maxCellLightCount : Dynamic;
	var _cellsDirty : Bool;
	function destroy():Void;
	function releaseClusterTexture():Void;
	function registerUniforms(device:Dynamic):Void;
	var _clusterSkipId : Dynamic;
	var _clusterMaxCellsId : Dynamic;
	var _clusterWorldTextureId : Dynamic;
	var _clusterTextureSizeId : Dynamic;
	var _clusterTextureSizeData : js.lib.Float32Array;
	var _clusterBoundsMinId : Dynamic;
	var _clusterBoundsMinData : js.lib.Float32Array;
	var _clusterBoundsDeltaId : Dynamic;
	var _clusterBoundsDeltaData : js.lib.Float32Array;
	var _clusterCellsCountByBoundsSizeId : Dynamic;
	var _clusterCellsCountByBoundsSizeData : js.lib.Float32Array;
	var _clusterCellsDotId : Dynamic;
	var _clusterCellsDotData : js.lib.Float32Array;
	var _clusterCellsMaxId : Dynamic;
	var _clusterCellsMaxData : js.lib.Float32Array;
	var _clusterCompressionLimit0Id : Dynamic;
	var _clusterCompressionLimit0Data : js.lib.Float32Array;
	function updateParams(lightingParams:Dynamic):Void;
	function updateCells():Void;
	var clusters : js.lib.Uint8ClampedArray;
	var counts : js.lib.Int32Array;
	function uploadTextures():Void;
	function updateUniforms():Void;
	function evalLightCellMinMax(clusteredLight:Dynamic, min:Dynamic, max:Dynamic):Void;
	function collectLights(lights:Dynamic):Void;
	function evaluateBounds():Void;
	function evaluateCompressionLimits(gammaCorrection:Dynamic):Void;
	function updateClusters(gammaCorrection:Dynamic):Void;
	function update(lights:Dynamic, gammaCorrection:Dynamic, lightingParams:Dynamic):Void;
	function activate():Void;
	static var prototype : WorldClusters;
}